language: node_js
node_js:
  - 10
before_script:
  - npm install
script: npm run-script test-headless && npm run build && npm run build-pro && npm run manage:plugins:staging && npm run manage:plugins:pro && npm run lint
