export const START_PLATFORMAUTHN_REGISTRATION = "START_PLATFORMAUTHN_REGISTRATION";
export const POST_PLATFORMAUTHN_REGISTRATION_FAIL = "POST_WEBAUTHN_WEBAUTHN_REGISTER_BEGIN_FAIL";
export const POST_PLATFORMAUTHN_REGISTRATION_SUCCESS = "POST_WEBAUTHN_WEBAUTHN_REGISTER_BEGIN_SUCCESS";

export const startRegisterPlatformAuthn = () => ({
  type: START_PLATFORMAUTHN_REGISTRATION,
});

export const postRegisterPlatformAuthnFail = () => ({
  type: POST_PLATFORMAUTHN_REGISTRATION_FAIL,
});

