# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:
  unittests:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run tests
        run: |
          make test

  audit_prod:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Audit production npm packages
        run: npx audit-ci --skip-dev --config audit-ci.json

  audit_dev:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Audit including devDependencies
        # Don't error out on audit warnings about devDependencies
        run: npx audit-ci --config audit-ci.json || true

  linter:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint
